apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-directory-raven
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: pv-name-raven