apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: raven-server
  labels:
    server-category: uat
    php-version: "7.2"
    id: raven
spec:
  replicas: 3
  serviceName: apache
  selector:
    matchLabels:
      server-category: uat
      php-version: "7.2"
      id: raven
  template:
    metadata:
      labels:
        server-category: uat
        php-version: "7.2"
        id: raven
    spec:
      containers:
        - name: raven-server
          image: "orangehrm/orangehrm-environment-images:uat-7.2-centos"
          ports:
            - containerPort: 443
            - containerPort: 22
          volumeMounts:
            - mountPath: /var/www/html
              name: web-directory
          command: ["/bin/bash","-c"]
          args: ["/usr/sbin/sshd-keygen; /usr/sbin/sshd -D &"]

      volumes:
        - name: web-directory
          persistentVolumeClaim:
            claimName: web-directory