apiVersion: v1
kind: Service
metadata:
  name: httpd-port-service
spec:
  type: NodePort
  ports:
    - targetPort: 443
      nodePort: 30008
      port: 443
    - targetPort: 80
      nodePort: 30009
      port: 80
  selector:
    category: test-1