apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-server
  labels:
    php-version: "7.2"
    id: app-server
spec:
  replicas: 2
  selector:
    matchLabels:
      id: app-server
  template:
    metadata:
      labels:
        id: app-server
    spec:
      containers:
        - name: web-server
          image: "orangehrm/orangehrm-environment-images:uat-7.2-centos"
          ports:
            - containerPort: 443
            - containerPort: 22
          volumeMounts:
            - mountPath: /var/www/html
              name: web-directory
          securityContext:
            privileged: true
      volumes:
        - name: web-directory
          persistentVolumeClaim:
            claimName: web-directory