apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-proxy
  labels:
    php-version: "7.2"
    id: db-proxy
spec:
  replicas: 2
  selector:
    matchLabels:
      id: db-proxy
  template:
    metadata:
      labels:
        id: db-proxy
    spec:
      containers:
        - name: proxy-server
          image: "orangehrm/orangehrm-environment-images:uat-7.2-centos"
          ports:
            - containerPort: 22
              name: ssh
            - containerPort: 4008
              name: 'mysql-r-port'
            - containerPort: 4006
              name: 'mysql-rw-port'
          securityContext:
            privileged: true