apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-name-raven
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data-raven"
    type: DirectoryOrCreate